import { createSlice } from '@reduxjs/toolkit';

/**
 * counterSlice: A "Slice" is a collection of Redux reducer logic and actions 
 * for a single feature in your app.
 * 
 * CORE CONCEPTS:
 * 1. State: The data we want to manage (initialState).
 * 2. Actions: Objects that describe what happened (automatically generated by createSlice).
 * 3. Reducers: Functions that take the current state and an action, and return a new state.
 */

const initialState = {
  value: 0,
};

export const counterSlice = createSlice({
  name: 'counter',
  initialState,
  reducers: {
    // Action: increment
    increment: (state) => {
      // Redux Toolkit allows us to write "mutating" logic in reducers. 
      // It doesn't actually mutate the state because it uses the Immer library,
      // which detects changes to a "draft state" and produces a brand new
      // immutable state based off those changes.
      state.value += 1;
    },
    // Action: decrement
    decrement: (state) => {
      state.value -= 1;
    },
    // Action: incrementByAmount (Action with Payload)
    incrementByAmount: (state, action) => {
      state.value += action.payload;
    },
  },
});

// Action creators are generated for each case reducer function
export const { increment, decrement, incrementByAmount } = counterSlice.actions;

// The reducer function as default export
export default counterSlice.reducer;
